INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');


INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Pluna - Boeing 737 - CX-BHM', 'https://d1o6h00a1h5k7q.cloudfront.net/imagens/img_g/18775/8739292.jpg', '01/07/1971', '01/07/1971', 'Montevideo - Carrasco', 'São Paulo - Congonhas', 'inter'  , 160) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Pluna - Boeing 737 - CX-BHM', 'https://d1o6h00a1h5k7q.cloudfront.net/imagens/img_g/18775/8739292.jpg', '09/07/1971', '09/07/1971', 'São Paulo - Congonhas', 'Montevideo - Carrasco', 'inter'  , 160) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'TAP - Boeing 707 - MATR', 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Boeing_707-382B%2C_TAP_-_Transportes_Aereos_Portugueses_AN1918746.jpg', '01/07/1975', '02/07/1975', 'Lisboa - Recife', 'Rio de Janeiro - Galeao', 'inter'  , 170) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'TAP - Boeing 707 - MATR', 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Boeing_707-382B%2C_TAP_-_Transportes_Aereos_Portugueses_AN1918746.jpg', '01/07/1975', '02/07/1975', 'Lisboa - Lisboa', 'Rio de Janeiro - Recife', 'inter'  , 450) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Iberia - Caravelle - MATR', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Iberia_Caravelle_Fitzgerald.jpg', '02/07/1975', '02/07/1975', 'Madri - Madri', 'Lisboa - Lisboa', 'inter'  , 80) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Iberia - Caravelle - MATR', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Iberia_Caravelle_Fitzgerald.jpg', '30/07/1975', '30/07/1975', 'Lisboa - Lisboa', 'Madri - Madrid', 'inter'  , 80) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'TAP - Boeing 707 - MATR', 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Boeing_707-382B%2C_TAP_-_Transportes_Aereos_Portugueses_AN1918746.jpg', '01/07/1975', '02/07/1975', 'Lisboa - Recife', 'Rio de Janeiro - Lisboa ', 'inter'  , 450) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'TAP - Boeing 707 - MATR', 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Boeing_707-382B%2C_TAP_-_Transportes_Aereos_Portugueses_AN1918746.jpg', '30/07/1975', '31/07/1975', 'Rio de Janeiro - Galeao', 'Lisboa - Recife', 'inter'  , 170) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American? Panan?Varig? - Boeing 747 ? - MATR', 'https://aeroin.net/wp-content/uploads/2019/09/AMERICAN-747-AEROIN-2.jpg', '29/03/1989', '30/03/1989', 'Nova York - Kennedy', 'São Paulo - Guarulhos', 'inter'  , 590) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American Eagle? - Dash8? - MATR', 'https://airlinesfleet.com/wp-content/uploads/2018/06/American-Eagle-Piedmont-Airlines-Bombardier-Dash-8-300-N336EN-landing-on-18L.jpg', '30/03/1989', '30/03/1989', 'Washington - National', 'Nova York - Kennedy?LG?', 'inter'  , 80) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Delta ? - DC10 ? - MATR', 'https://photos-e1.flightcdn.com/photos/retriever/7fb534238f3de26eeadadf5b88dbc43cc7cf3c08', '30/03/1989', '30/03/1989', 'Dallas - Dallas-FW', 'Washington? - National', 'inter'  , 220) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American Eagle? - Bandeirante? - MATR', 'https://www.airhistory.net/photos/0282111.jpg', '30/03/1989', '30/03/1989', 'College Station - College ST', 'Dallas  - Dallas-FW', 'inter'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American Eagle? - Bandeirante? - MATR', 'https://www.airhistory.net/photos/0282111.jpg', '30/03/1989', '30/03/1989', 'Dallas  - Dallas-FW', 'College Station - College ST', 'inter'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Delta ? - DC10 ? - MATR', 'https://photos-e1.flightcdn.com/photos/retriever/7fb534238f3de26eeadadf5b88dbc43cc7cf3c08', '30/03/1989', '30/03/1989', 'Washington? - National', 'Dallas - Dallas-FW', 'inter'  , 220) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American Eagle? - Dash8? - MATR', 'https://airlinesfleet.com/wp-content/uploads/2018/06/American-Eagle-Piedmont-Airlines-Bombardier-Dash-8-300-N336EN-landing-on-18L.jpg', '14/04/1989', '14/04/1989', 'Nova York - Kennedy?LG?', 'Washington - National', 'inter'  , 80) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American? Panan?Varig? - Boeing 747 ? - MATR', 'https://aeroin.net/wp-content/uploads/2019/09/AMERICAN-747-AEROIN-2.jpg', '15/04/1989', '16/04/1989', 'São Paulo - Guarulhos', 'Nova York - Kennedy', 'inter'  , 590) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American? Panan?Varig? - Boeing 747 ? - MATR', 'https://aeroin.net/wp-content/uploads/2019/11/VARIG-PP-VNA.jpg', '01/09/1990', '02/09/1990', 'Nova York - Kennedy', 'São Paulo - Guarulhos', 'inter'  , 590) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'United - Boeing ? - MATR', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg', '01/09/1990', '02/09/1990', 'Washington - Dulles?', 'Nova York - Kennedy?LG?', 'inter'  , 80) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'United - Boeing ? - MATR', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg', '01/09/1990', '02/09/1990', 'Minneapolis - Minneapolis', 'Washington? - Dulles', 'inter'  , 145) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'United - Boeing ? - MATR', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg', '01/09/1990', '02/09/1990', 'Columbia - Columbia', 'Minneapolis - Minneapolis', 'inter'  , 280) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'United - Boeing ? - MATR', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg', '01/09/1990', '02/09/1990', 'Chicago - Ohare', 'Columbia - Columbia', 'inter'  , 240) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'United - Boeing ? - MATR', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg', '01/09/1990', '02/09/1990', 'San Diego - San Diego', 'Chicago - Ohare', 'inter'  , 270) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'United - Boeing ? - MATR', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg', '01/09/1990', '02/09/1990', 'San Francisco - San Francisco', 'Los Angeles - Los Angeles', 'inter'  , 90) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'United - Boeing ? - MATR', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg', '01/09/1990', '02/09/1990', 'Nova York - Kennedy?LG?', 'San Francisco - San Francisco', 'inter'  , 325) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American? Panan?Varig? - Boeing 747 ? - MATR', 'https://aeroin.net/wp-content/uploads/2019/11/VARIG-PP-VNA.jpg', '01/09/1990', '02/09/1990', 'São Paulo - Guarulhos', 'Nova York - Kennedy', 'inter'  , 590) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American? United?Varig? - Boeing 747 ? - MATR', 'https://cdn.planespotters.net/photo/708000/original/n755pa-pan-american-world-airways-pan-am-boeing-747-121_PlanespottersNet_708497_46cafb0c88.jpg', '09/07/1993', '10/07/1993', 'Miami - Miami', 'São Paulo - Guarulhos', 'inter'  , 505) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American? United? - Boeing ? - MATR', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg', '24/07/1993', '24/07/1993', 'Hartford - Hartford', 'Miami - Miami', 'inter'  , 185) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American? United? - Boeing  ? - MATR', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg', '30/07/1993', '30/07/1993', 'Miami - Miami', 'Hartford - Hartford', 'inter'  , 185) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'American? United?Varig? - Boeing 747 ? - MATR', 'https://cdn.planespotters.net/photo/708000/original/n755pa-pan-american-world-airways-pan-am-boeing-747-121_PlanespottersNet_708497_46cafb0c88.jpg', '30/07/1993', '31/07/1993', 'São Paulo - Guarulhos', 'Miami - Miami', 'inter'  , 505) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig ? - Boeing 767 - MATR', 'https://avioesemusicas.com/wp-content/uploads/2013/09/PP-VNN294.jpg', '09/06/1996', '10/06/1996', 'Madri - Madri', 'São Paulo - Guarulhos', 'inter'  , 615) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Iberia ? - Boeing ? - MATR', 'https://upload.wikimedia.org/wikipedia/commons/b/b3/B-_737_Iberia.jpg', '09/06/1996', '10/06/1996', 'Barcelona - Barcelona', 'Madri - Madri', 'inter'  , 80) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Iberia ? - Boeing  ? - MATR', 'https://upload.wikimedia.org/wikipedia/commons/b/b3/B-_737_Iberia.jpg', '17/06/1996', '17/06/1996', 'Madri - Madri', 'Barcelona - Barcelona', 'inter'  , 80) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig ? - Boeing 767 - MATR', 'https://avioesemusicas.com/wp-content/uploads/2013/09/PP-VNN294.jpg', '18/06/1996', '18/06/1996', 'São Paulo - Guarulhos', 'Madri - Madri', 'inter'  , 615) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '01/04/1984', '01/04/1984', 'Rio de Janeiro - Santos Dumont', 'São Paulo - Congonhas', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '05/04/1984', '05/04/1984', 'São Paulo - Congonhas', 'Rio de janeiro - Santos Dumont', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '01/04/1985', '01/04/1985', 'Rio de Janeiro - Santos Dumont', 'São Paulo - Congonhas', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '05/04/1985', '05/04/1985', 'São Paulo - Congonhas', 'Rio de janeiro - Santos Dumont', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '01/05/1985', '05/05/1985', 'Rio de Janeiro - Santos Dumont', 'São Paulo - Congonhas', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '01/05/1985', '05/05/1985', 'São Paulo - Congonhas', 'Rio de janeiro - Santos Dumont', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '01/06/1985', '05/06/1985', 'Rio de Janeiro - Santos Dumont', 'São Paulo - Congonhas', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '01/06/1985', '05/06/1985', 'São Paulo - Congonhas', 'Rio de janeiro - Santos Dumont', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '01/04/1986', '01/04/1986', 'Rio de Janeiro - Santos Dumont', 'São Paulo - Congonhas', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '05/04/1986', '05/04/1986', 'São Paulo - Congonhas', 'Rio de janeiro - Santos Dumont', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '01/09/1989', '01/09/1989', 'Rio de Janeiro - Santos Dumont', 'São Paulo - Congonhas', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '05/09/1989', '05/09/1989', 'São Paulo - Congonhas', 'Rio de janeiro - Santos Dumont', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '01/10/1989', '01/10/1989', 'Rio de Janeiro - Santos Dumont', 'São Paulo - Congonhas', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Electra - MATR', 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg', '05/10/1989', '05/10/1989', 'São Paulo - Congonhas', 'Rio de janeiro - Santos Dumont', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'TAM - Fokker 100 - MATR', 'https://aventurasnahistoria.uol.com.br/media/uploads/avioes/fokker_100_1.jpg', '01/04/2001', '01/04/2001', 'Rio de Janeiro - Santos Dumont', 'São Paulo - Congonhas', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'TAM - Fokker 101 - MATR', 'https://aventurasnahistoria.uol.com.br/media/uploads/avioes/fokker_100_1.jpg', '05/04/2001', '05/04/2001', 'São Paulo - Congonhas', 'Rio de janeiro - Santos Dumont', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://aeroin.net/wp-content/uploads/2020/10/727-varig-pp-vld-1024x664.jpg', '01/04/1984', '01/04/1984', 'Porto Alegre - Porto Alegre', 'São Paulo - Congonhas', 'nacional'  , 100) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://aeroin.net/wp-content/uploads/2020/10/727-varig-pp-vld-1024x664.jpg', '05/04/1984', '05/04/1984', 'São Paulo - Congonhas', 'Porto Alegre - Porto Alegre', 'nacional'  , 100) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://aeroin.net/wp-content/uploads/2020/10/727-varig-pp-vld-1024x664.jpg', '01/04/1985', '01/04/1985', 'Porto Alegre - Porto Alegre', 'São Paulo - Congonhas', 'nacional'  , 100) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://aeroin.net/wp-content/uploads/2020/10/727-varig-pp-vld-1024x664.jpg', '05/04/1985', '05/04/1985', 'São Paulo - Congonhas', 'Porto Alegre - Porto Alegre', 'nacional'  , 100) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Cruzeiro - Airbus a300 - MATR', 'https://img.comunidades.net/avi/avicom/Cruzeiro_do_Sul_Airbus_A300.jpg', '01/06/1990', '01/06/1990', 'Porto Alegre - Porto Alegre', 'São Paulo - Congonhas', 'nacional'  , 100) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Cruzeiro - Airbus a300 - MATR', 'https://img.comunidades.net/avi/avicom/Cruzeiro_do_Sul_Airbus_A300.jpg', '05/06/1990', '05/06/1990', 'São Paulo - Congonhas', 'Porto Alegre - Porto Alegre', 'nacional'  , 100) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Cruzeiro - Airbus a300 - MATR', 'https://img.comunidades.net/avi/avicom/Cruzeiro_do_Sul_Airbus_A300.jpg', '01/07/1990', '01/07/1990', 'Porto Alegre - Porto Alegre', 'São Paulo - Congonhas', 'nacional'  , 100) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Cruzeiro - Airbus a300 - MATR', 'https://img.comunidades.net/avi/avicom/Cruzeiro_do_Sul_Airbus_A300.jpg', '05/07/1990', '05/07/1990', 'São Paulo - Congonhas', 'Porto Alegre - Porto Alegre', 'nacional'  , 100) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '01/06/1990', '01/06/1990', 'Curitiba - Curitiba', 'São Paulo - Congonhas', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '05/06/1990', '05/06/1990', 'São Paulo - Congonhas', 'Curitiba - Curitiba', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '01/07/1990', '01/07/1990', 'Curitiba - Curitiba', 'São Paulo - Congonhas', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '05/07/1990', '05/07/1990', 'São Paulo - Congonhas', 'Curitiba - Curitiba', 'nacional'  , 60) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '01/06/1990', '01/06/1990', 'Florianopolis - Florianopolis', 'São Paulo - Congonhas', 'nacional'  , 75) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '05/06/1990', '05/06/1990', 'São Paulo - Congonhas', 'Florianopolis - Florianopolis', 'nacional'  , 75) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '01/07/1990', '01/07/1990', 'Florianopolis - Florianopolis', 'São Paulo - Congonhas', 'nacional'  , 75) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '05/07/1990', '05/07/1990', 'São Paulo - Congonhas', 'Florianopolis - Florianopolis', 'nacional'  , 75) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '01/06/1990', '01/06/1990', 'Belo Horizonte - Belo Horizonte', 'São Paulo - Congonhas', 'nacional'  , 70) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '05/06/1990', '05/06/1990', 'São Paulo - Congonhas', 'Belo Horizonte - Belo Horizonte', 'nacional'  , 70) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '01/07/1990', '01/07/1990', 'Belo Horizonte - Belo Horizonte', 'São Paulo - Congonhas', 'nacional'  , 70) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '05/07/1990', '05/07/1990', 'São Paulo - Congonhas', 'Belo Horizonte - Belo Horizonte', 'nacional'  , 70) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '01/06/1990', '01/06/1990', 'Brasilia - Brasilia', 'São Paulo - Congonhas', 'nacional'  , 100) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '05/06/1990', '05/06/1990', 'São Paulo - Congonhas', 'Brasilia - Brasilia', 'nacional'  , 100) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '01/07/1990', '01/07/1990', 'Brasilia - Brasilia', 'São Paulo - Congonhas', 'nacional'  , 100) ; 
INSERT INTO tb_flight(score, count, title, image, data_chegada, data_partida, destino, origem, tipo_voo, duracao) VALUES (0, 0, 'Varig - Boeing  - MATR', 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg', '05/07/1990', '05/07/1990', 'São Paulo - Congonhas', 'Brasilia - Brasilia', 'nacional'  , 100) ; 



INSERT INTO tb_score(flight_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(flight_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(flight_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(flight_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(flight_id, user_id, value) VALUES (2, 3, 4.0);

INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Pluna - Boeing 737 - CX-BHM' , 0 , 0 , 'https://d1o6h00a1h5k7q.cloudfront.net/imagens/img_g/18775/8739292.jpg' , 'Congonhas' , 'Carrasco' , 'São Paulo' , 'Montevideo' , 'Brasil' , 'Uruguai' , 160 , '01/07/1971' , '01/07/1971' , 'inter' , 'Boeing 737' , 'CX-BHM' , 'Pluna' , '' , 'Palmeiras Fut Sal')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Pluna - Boeing 737 - CX-BHM' , 0 , 0 , 'https://d1o6h00a1h5k7q.cloudfront.net/imagens/img_g/18775/8739292.jpg' , 'Carrasco' , 'Congonhas' , 'Montevideo' , 'São Paulo' , 'Uruguai' , 'Brasil' , 160 , '09/07/1971' , '09/07/1971' , 'inter' , 'Boeing 737' , 'CX-BHM' , 'Pluna' , '' , 'Palmeiras Fut Sal')

INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('TAP - Boeing 707 - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Boeing_707-382B%2C_TAP_-_Transportes_Aereos_Portugueses_AN1918746.jpg' , 'Galeao' , 'Recife' , 'Rio de Janeiro' , 'Lisboa' , 'Brasil' , 'Portugal' , 170 , '01/07/1975' , '02/07/1975' , 'inter' , 'Boeing 707' , 'MATR' , 'TAP' , 'Recife' , 'Candinho Copa Noruega')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('TAP - Boeing 707 - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Boeing_707-382B%2C_TAP_-_Transportes_Aereos_Portugueses_AN1918746.jpg' , 'Recife' , 'Lisboa' , 'Rio de Janeiro' , 'Lisboa' , 'Brasil' , 'Portugal' , 450 , '01/07/1975' , '02/07/1975' , 'inter' , 'Boeing 707' , 'MATR' , 'TAP' , 'Recife' , 'Candinho Copa Noruega')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Iberia - Caravelle - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Iberia_Caravelle_Fitzgerald.jpg' , 'Lisboa' , 'Madri' , 'Lisboa' , 'Madri' , 'Portugal' , 'Espanha' , 80 , '02/07/1975' , '02/07/1975' , 'inter' , 'Caravelle' , 'MATR' , 'Iberia' , '' , 'Candinho Copa Noruega')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Iberia - Caravelle - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Iberia_Caravelle_Fitzgerald.jpg' , 'Madrid' , 'Lisboa' , 'Madri' , 'Lisboa' , 'Espanha' , 'Portugal' , 80 , '30/07/1975' , '30/07/1975' , 'inter' , 'Caravelle' , 'MATR' , 'Iberia' , '' , 'Candinho Copa Noruega')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('TAP - Boeing 707 - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Boeing_707-382B%2C_TAP_-_Transportes_Aereos_Portugueses_AN1918746.jpg' , 'Lisboa ' , 'Recife' , 'Rio de Janeiro' , 'Lisboa' , 'Brasil' , 'Portugal' , 450 , '01/07/1975' , '02/07/1975' , 'inter' , 'Boeing 707' , 'MATR' , 'TAP' , 'Recife' , 'Candinho Copa Noruega')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('TAP - Boeing 707 - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Boeing_707-382B%2C_TAP_-_Transportes_Aereos_Portugueses_AN1918746.jpg' , 'Recife' , 'Galeao' , 'Lisboa' , 'Rio de Janeiro' , 'Portugal' , 'Brasil' , 170 , '30/07/1975' , '31/07/1975' , 'inter' , 'Boeing 707' , 'MATR' , 'TAP' , 'Recife' , 'Candinho Copa Noruega')

INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American? Panan?Varig? - Boeing 747 ? - MATR' , 0 , 0 , 'https://aeroin.net/wp-content/uploads/2019/09/AMERICAN-747-AEROIN-2.jpg' , 'Guarulhos' , 'Kennedy' , 'São Paulo' , 'Nova York' , 'Brasil' , 'Estados Unidos' , 590 , '29/03/1989' , '30/03/1989' , 'inter' , 'Boeing 747 ?' , 'MATR' , 'American? Panan?Varig?' , '' , 'NCR CUE Washington')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American Eagle? - Dash8? - MATR' , 0 , 0 , 'https://airlinesfleet.com/wp-content/uploads/2018/06/American-Eagle-Piedmont-Airlines-Bombardier-Dash-8-300-N336EN-landing-on-18L.jpg' , 'Kennedy?LG?' , 'National' , 'Nova York' , 'Washington' , 'Estados Unidos' , 'Estados Unidos' , 80 , '30/03/1989' , '30/03/1989' , 'inter' , 'Dash8?' , 'MATR' , 'American Eagle?' , '' , 'NCR CUE Washington')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Delta ? - DC10 ? - MATR' , 0 , 0 , 'https://photos-e1.flightcdn.com/photos/retriever/7fb534238f3de26eeadadf5b88dbc43cc7cf3c08' , 'National' , 'Dallas-FW' , 'Washington?' , 'Dallas' , 'Estados Unidos' , 'Estados Unidos' , 220 , '30/03/1989' , '30/03/1989' , 'inter' , 'DC10 ?' , 'MATR' , 'Delta ?' , 'Atlanta ?' , 'NCR CUE Washington')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American Eagle? - Bandeirante? - MATR' , 0 , 0 , 'https://www.airhistory.net/photos/0282111.jpg' , 'Dallas-FW' , 'College ST' , 'Dallas ' , 'College Station' , 'Estados Unidos' , 'Estados Unidos' , 60 , '30/03/1989' , '30/03/1989' , 'inter' , 'Bandeirante?' , 'MATR' , 'American Eagle?' , '' , 'NCR CUE Washington')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American Eagle? - Bandeirante? - MATR' , 0 , 0 , 'https://www.airhistory.net/photos/0282111.jpg' , 'College ST' , 'Dallas-FW' , 'College Station' , 'Dallas ' , 'Estados Unidos' , 'Estados Unidos' , 60 , '30/03/1989' , '30/03/1989' , 'inter' , 'Bandeirante?' , 'MATR' , 'American Eagle?' , '' , 'NCR CUE Washington')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Delta ? - DC10 ? - MATR' , 0 , 0 , 'https://photos-e1.flightcdn.com/photos/retriever/7fb534238f3de26eeadadf5b88dbc43cc7cf3c08' , 'Dallas-FW' , 'National' , 'Dallas' , 'Washington?' , 'Estados Unidos' , 'Estados Unidos' , 220 , '30/03/1989' , '30/03/1989' , 'inter' , 'DC10 ?' , 'MATR' , 'Delta ?' , 'Atlanta ?' , 'NCR CUE Washington')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American Eagle? - Dash8? - MATR' , 0 , 0 , 'https://airlinesfleet.com/wp-content/uploads/2018/06/American-Eagle-Piedmont-Airlines-Bombardier-Dash-8-300-N336EN-landing-on-18L.jpg' , 'National' , 'Kennedy?LG?' , 'Washington' , 'Nova York' , 'Estados Unidos' , 'Estados Unidos' , 80 , '14/04/1989' , '14/04/1989' , 'inter' , 'Dash8?' , 'MATR' , 'American Eagle?' , '' , 'NCR CUE Washington')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American? Panan?Varig? - Boeing 747 ? - MATR' , 0 , 0 , 'https://aeroin.net/wp-content/uploads/2019/09/AMERICAN-747-AEROIN-2.jpg' , 'Kennedy' , 'Guarulhos' , 'Nova York' , 'São Paulo' , 'Estados Unidos' , 'Brasil' , 590 , '15/04/1989' , '16/04/1989' , 'inter' , 'Boeing 747 ?' , 'MATR' , 'American? Panan?Varig?' , '' , 'NCR CUE Washington')

INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American? Panan?Varig? - Boeing 747 ? - MATR' , 0 , 0 , 'https://aeroin.net/wp-content/uploads/2019/11/VARIG-PP-VNA.jpg' , 'Guarulhos' , 'Kennedy' , 'São Paulo' , 'Nova York' , 'Brasil' , 'Estados Unidos' , 590 , '01/09/1990' , '02/09/1990' , 'inter' , 'Boeing 747 ?' , 'MATR' , 'American? Panan?Varig?' , '' , 'NCR CUE San Diego')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('United - Boeing ? - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg' , 'Kennedy?LG?' , 'Dulles?' , 'Nova York' , 'Washington' , 'Estados Unidos' , 'Estados Unidos' , 80 , '01/09/1990' , '02/09/1990' , 'inter' , 'Boeing ?' , 'MATR' , 'United' , '' , 'NCR CUE San Diego')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('United - Boeing ? - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg' , 'Dulles' , 'Minneapolis' , 'Washington?' , 'Minneapolis' , 'Estados Unidos' , 'Estados Unidos' , 145 , '01/09/1990' , '02/09/1990' , 'inter' , 'Boeing ?' , 'MATR' , 'United' , 'Charlotte' , 'NCR CUE San Diego')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('United - Boeing ? - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg' , 'Minneapolis' , 'Columbia' , 'Minneapolis' , 'Columbia' , 'Estados Unidos' , 'Estados Unidos' , 280 , '01/09/1990' , '02/09/1990' , 'inter' , 'Boeing ?' , 'MATR' , 'United' , '' , 'NCR CUE San Diego')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('United - Boeing ? - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg' , 'Columbia' , 'Ohare' , 'Columbia' , 'Chicago' , 'Estados Unidos' , 'Estados Unidos' , 240 , '01/09/1990' , '02/09/1990' , 'inter' , 'Boeing ?' , 'MATR' , 'United' , 'Charlotte' , 'NCR CUE San Diego')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('United - Boeing ? - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg' , 'Ohare' , 'San Diego' , 'Chicago' , 'San Diego' , 'Estados Unidos' , 'Estados Unidos' , 270 , '01/09/1990' , '02/09/1990' , 'inter' , 'Boeing ?' , 'MATR' , 'United' , '' , 'NCR CUE San Diego')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('United - Boeing ? - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg' , 'Los Angeles' , 'San Francisco' , 'Los Angeles' , 'San Francisco' , 'Estados Unidos' , 'Estados Unidos' , 90 , '01/09/1990' , '02/09/1990' , 'inter' , 'Boeing ?' , 'MATR' , 'United' , '' , 'NCR CUE San Diego')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('United - Boeing ? - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg' , 'San Francisco' , 'Kennedy?LG?' , 'San Francisco' , 'Nova York' , 'Estados Unidos' , 'Estados Unidos' , 325 , '01/09/1990' , '02/09/1990' , 'inter' , 'Boeing ?' , 'MATR' , 'United' , '' , 'NCR CUE San Diego')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American? Panan?Varig? - Boeing 747 ? - MATR' , 0 , 0 , 'https://aeroin.net/wp-content/uploads/2019/11/VARIG-PP-VNA.jpg' , 'Kennedy' , 'Guarulhos' , 'Nova York' , 'São Paulo' , 'Estados Unidos' , 'Brasil' , 590 , '01/09/1990' , '02/09/1990' , 'inter' , 'Boeing 747 ?' , 'MATR' , 'American? Panan?Varig?' , '' , 'NCR CUE San Diego')

INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American? United?Varig? - Boeing 747 ? - MATR' , 0 , 0 , 'https://cdn.planespotters.net/photo/708000/original/n755pa-pan-american-world-airways-pan-am-boeing-747-121_PlanespottersNet_708497_46cafb0c88.jpg' , 'Guarulhos' , 'Miami' , 'São Paulo' , 'Miami' , 'Brasil' , 'Estados Unidos' , 505 , '09/07/1993' , '10/07/1993' , 'inter' , 'Boeing 747 ?' , 'MATR' , 'American? United?Varig?' , '' , 'Telematics/Cisco')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American? United? - Boeing ? - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg' , 'Miami' , 'Hartford' , 'Miami' , 'Hartford' , 'Estados Unidos' , 'Estados Unidos' , 185 , '24/07/1993' , '24/07/1993' , 'inter' , 'Boeing ?' , 'MATR' , 'American? United?' , '' , 'Telematics/Cisco')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American? United? - Boeing  ? - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/e/ef/United_Airlines_Boeing_737-222%3B_N9075U%2C_April_1990_CRO_%285057344444%29.jpg' , 'Hartford' , 'Miami' , 'Hartford' , 'Miami' , 'Estados Unidos' , 'Estados Unidos' , 185 , '30/07/1993' , '30/07/1993' , 'inter' , 'Boeing  ?' , 'MATR' , 'American? United?' , '' , 'Telematics/Cisco')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('American? United?Varig? - Boeing 747 ? - MATR' , 0 , 0 , 'https://cdn.planespotters.net/photo/708000/original/n755pa-pan-american-world-airways-pan-am-boeing-747-121_PlanespottersNet_708497_46cafb0c88.jpg' , 'Miami' , 'Guarulhos' , 'Miami' , 'São Paulo' , 'Brasil' , 'Estados Unidos' , 505 , '30/07/1993' , '31/07/1993' , 'inter' , 'Boeing 747 ?' , 'MATR' , 'American? United?Varig?' , '' , 'Telematics/Cisco')

INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig ? - Boeing 767 - MATR' , 0 , 0 , 'https://avioesemusicas.com/wp-content/uploads/2013/09/PP-VNN294.jpg' , 'Guarulhos' , 'Madri' , 'São Paulo' , 'Madri' , 'Brasil' , 'Espanha' , 615 , '09/06/1996' , '10/06/1996' , 'inter' , 'Boeing 767' , 'MATR' , 'Varig ?' , '' , 'CPM/Telematics')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Iberia ? - Boeing ? - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/b/b3/B-_737_Iberia.jpg' , 'Madri' , 'Barcelona' , 'Madri' , 'Barcelona' , 'Espanha' , 'Barcelona' , 80 , '09/06/1996' , '10/06/1996' , 'inter' , 'Boeing ?' , 'MATR' , 'Iberia ?' , '' , 'CPM/Telematics')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Iberia ? - Boeing  ? - MATR' , 0 , 0 , 'https://upload.wikimedia.org/wikipedia/commons/b/b3/B-_737_Iberia.jpg' , 'Barcelona' , 'Madri' , 'Barcelona' , 'Madri' , 'Espanha' , 'Madri' , 80 , '17/06/1996' , '17/06/1996' , 'inter' , 'Boeing  ?' , 'MATR' , 'Iberia ?' , '' , 'CPM/Telematics')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig ? - Boeing 767 - MATR' , 0 , 0 , 'https://avioesemusicas.com/wp-content/uploads/2013/09/PP-VNN294.jpg' , 'Madri' , 'Guarulhos' , 'Madri' , 'São Paulo' , 'Espanha' , 'Brasil' , 615 , '18/06/1996' , '18/06/1996' , 'inter' , 'Boeing 767' , 'MATR' , 'Varig ?' , '' , 'CPM/Telematics')




INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Congonhas' , 'Santos Dumont' , 'São Paulo' , 'Rio de Janeiro' , 'Brasil' , 'Brasil' , 60 , '01/04/1984' , '01/04/1984' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Implantacao CICS-RJ')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Santos Dumont' , 'Congonhas' , 'Rio de janeiro' , 'São Paulo' , 'Brasil' , 'Brasil' , 60 , '05/04/1984' , '05/04/1984' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Implantacao CICS-RJ')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Congonhas' , 'Santos Dumont' , 'São Paulo' , 'Rio de Janeiro' , 'Brasil' , 'Brasil' , 60 , '01/04/1985' , '01/04/1985' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Migracao DOS-MVS')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Santos Dumont' , 'Congonhas' , 'Rio de janeiro' , 'São Paulo' , 'Brasil' , 'Brasil' , 60 , '05/04/1985' , '05/04/1985' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Migracao DOS-MVS')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Congonhas' , 'Santos Dumont' , 'São Paulo' , 'Rio de Janeiro' , 'Brasil' , 'Brasil' , 60 , '01/05/1985' , '05/05/1985' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Migracao DOS-MVS')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Santos Dumont' , 'Congonhas' , 'Rio de janeiro' , 'São Paulo' , 'Brasil' , 'Brasil' , 60 , '01/05/1985' , '05/05/1985' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Migracao DOS-MVS')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Congonhas' , 'Santos Dumont' , 'São Paulo' , 'Rio de Janeiro' , 'Brasil' , 'Brasil' , 60 , '01/06/1985' , '05/06/1985' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Migracao DOS-MVS')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Santos Dumont' , 'Congonhas' , 'Rio de janeiro' , 'São Paulo' , 'Brasil' , 'Brasil' , 60 , '01/06/1985' , '05/06/1985' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Migracao DOS-MVS')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Congonhas' , 'Santos Dumont' , 'São Paulo' , 'Rio de Janeiro' , 'Brasil' , 'Brasil' , 60 , '01/04/1986' , '01/04/1986' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Embratel Victori Datasat BI')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Santos Dumont' , 'Congonhas' , 'Rio de janeiro' , 'São Paulo' , 'Brasil' , 'Brasil' , 60 , '05/04/1986' , '05/04/1986' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Embratel Victori Datasat BI')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Congonhas' , 'Santos Dumont' , 'São Paulo' , 'Rio de Janeiro' , 'Brasil' , 'Brasil' , 60 , '01/09/1989' , '01/09/1989' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Santos Dumont' , 'Congonhas' , 'Rio de janeiro' , 'São Paulo' , 'Brasil' , 'Brasil' , 60 , '05/09/1989' , '05/09/1989' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Congonhas' , 'Santos Dumont' , 'São Paulo' , 'Rio de Janeiro' , 'Brasil' , 'Brasil' , 60 , '01/10/1989' , '01/10/1989' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Electra - MATR' , 0 , 0 , 'https://contatoradar.com.br/wp-content/uploads/2018/05/ppvjm_sdu_18_08_76.jpg' , 'Santos Dumont' , 'Congonhas' , 'Rio de janeiro' , 'São Paulo' , 'Brasil' , 'Brasil' , 60 , '05/10/1989' , '05/10/1989' , 'nacional' , 'Electra' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('TAM - Fokker 100 - MATR' , 0 , 0 , 'https://aventurasnahistoria.uol.com.br/media/uploads/avioes/fokker_100_1.jpg' , 'Congonhas' , 'Santos Dumont' , 'São Paulo' , 'Rio de Janeiro' , 'Brasil' , 'Brasil' , 60 , '01/04/2001' , '01/04/2001' , 'nacional' , 'Fokker 100' , 'MATR' , 'TAM' , '' , 'Fininvest')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('TAM - Fokker 101 - MATR' , 0 , 0 , 'https://aventurasnahistoria.uol.com.br/media/uploads/avioes/fokker_100_1.jpg' , 'Santos Dumont' , 'Congonhas' , 'Rio de janeiro' , 'São Paulo' , 'Brasil' , 'Brasil' , 60 , '05/04/2001' , '05/04/2001' , 'nacional' , 'Fokker 101' , 'MATR' , 'TAM' , '' , 'Fininvest')

INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://aeroin.net/wp-content/uploads/2020/10/727-varig-pp-vld-1024x664.jpg' , 'Congonhas' , 'Porto Alegre' , 'São Paulo' , 'Porto Alegre' , 'Brasil' , 'Brasil' , 100 , '01/04/1984' , '01/04/1984' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao CICS-RS')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://aeroin.net/wp-content/uploads/2020/10/727-varig-pp-vld-1024x664.jpg' , 'Porto Alegre' , 'Congonhas' , 'Porto Alegre' , 'São Paulo' , 'Brasil' , 'Brasil' , 100 , '05/04/1984' , '05/04/1984' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao CICS-RS')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://aeroin.net/wp-content/uploads/2020/10/727-varig-pp-vld-1024x664.jpg' , 'Congonhas' , 'Porto Alegre' , 'São Paulo' , 'Porto Alegre' , 'Brasil' , 'Brasil' , 100 , '01/04/1985' , '01/04/1985' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Migracao DOS-MVS')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://aeroin.net/wp-content/uploads/2020/10/727-varig-pp-vld-1024x664.jpg' , 'Porto Alegre' , 'Congonhas' , 'Porto Alegre' , 'São Paulo' , 'Brasil' , 'Brasil' , 100 , '05/04/1985' , '05/04/1985' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Migracao DOS-MVS')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Cruzeiro - Airbus a300 - MATR' , 0 , 0 , 'https://img.comunidades.net/avi/avicom/Cruzeiro_do_Sul_Airbus_A300.jpg' , 'Congonhas' , 'Porto Alegre' , 'São Paulo' , 'Porto Alegre' , 'Brasil' , 'Brasil' , 100 , '01/06/1990' , '01/06/1990' , 'nacional' , 'Airbus a300' , 'MATR' , 'Cruzeiro' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Cruzeiro - Airbus a300 - MATR' , 0 , 0 , 'https://img.comunidades.net/avi/avicom/Cruzeiro_do_Sul_Airbus_A300.jpg' , 'Porto Alegre' , 'Congonhas' , 'Porto Alegre' , 'São Paulo' , 'Brasil' , 'Brasil' , 100 , '05/06/1990' , '05/06/1990' , 'nacional' , 'Airbus a300' , 'MATR' , 'Cruzeiro' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Cruzeiro - Airbus a300 - MATR' , 0 , 0 , 'https://img.comunidades.net/avi/avicom/Cruzeiro_do_Sul_Airbus_A300.jpg' , 'Congonhas' , 'Porto Alegre' , 'São Paulo' , 'Porto Alegre' , 'Brasil' , 'Brasil' , 100 , '01/07/1990' , '01/07/1990' , 'nacional' , 'Airbus a300' , 'MATR' , 'Cruzeiro' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Cruzeiro - Airbus a300 - MATR' , 0 , 0 , 'https://img.comunidades.net/avi/avicom/Cruzeiro_do_Sul_Airbus_A300.jpg' , 'Porto Alegre' , 'Congonhas' , 'Porto Alegre' , 'São Paulo' , 'Brasil' , 'Brasil' , 100 , '05/07/1990' , '05/07/1990' , 'nacional' , 'Airbus a300' , 'MATR' , 'Cruzeiro' , '' , 'Implantacao Comten')

INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Congonhas' , 'Curitiba' , 'São Paulo' , 'Curitiba' , 'Brasil' , 'Brasil' , 60 , '01/06/1990' , '01/06/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Curitiba' , 'Congonhas' , 'Curitiba' , 'São Paulo' , 'Brasil' , 'Brasil' , 60 , '05/06/1990' , '05/06/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Congonhas' , 'Curitiba' , 'São Paulo' , 'Curitiba' , 'Brasil' , 'Brasil' , 60 , '01/07/1990' , '01/07/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Curitiba' , 'Congonhas' , 'Curitiba' , 'São Paulo' , 'Brasil' , 'Brasil' , 60 , '05/07/1990' , '05/07/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')

INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Congonhas' , 'Florianopolis' , 'São Paulo' , 'Florianopolis' , 'Brasil' , 'Brasil' , 75 , '01/06/1990' , '01/06/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Florianopolis' , 'Congonhas' , 'Florianopolis' , 'São Paulo' , 'Brasil' , 'Brasil' , 75 , '05/06/1990' , '05/06/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Congonhas' , 'Florianopolis' , 'São Paulo' , 'Florianopolis' , 'Brasil' , 'Brasil' , 75 , '01/07/1990' , '01/07/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Florianopolis' , 'Congonhas' , 'Florianopolis' , 'São Paulo' , 'Brasil' , 'Brasil' , 75 , '05/07/1990' , '05/07/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')

INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Congonhas' , 'Belo Horizonte' , 'São Paulo' , 'Belo Horizonte' , 'Brasil' , 'Brasil' , 70 , '01/06/1990' , '01/06/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Belo Horizonte' , 'Congonhas' , 'Belo Horizonte' , 'São Paulo' , 'Brasil' , 'Brasil' , 70 , '05/06/1990' , '05/06/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Congonhas' , 'Belo Horizonte' , 'São Paulo' , 'Belo Horizonte' , 'Brasil' , 'Brasil' , 70 , '01/07/1990' , '01/07/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Belo Horizonte' , 'Congonhas' , 'Belo Horizonte' , 'São Paulo' , 'Brasil' , 'Brasil' , 70 , '05/07/1990' , '05/07/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')

INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Congonhas' , 'Brasilia' , 'São Paulo' , 'Brasilia' , 'Brasil' , 'Brasil' , 100 , '01/06/1990' , '01/06/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Brasilia' , 'Congonhas' , 'Brasilia' , 'São Paulo' , 'Brasil' , 'Brasil' , 100 , '05/06/1990' , '05/06/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Congonhas' , 'Brasilia' , 'São Paulo' , 'Brasilia' , 'Brasil' , 'Brasil' , 100 , '01/07/1990' , '01/07/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')
INSERT INTO tb_flightdetalhe (title, score, count, image, aeroportoorigem, aeroportodestino, cidadeorigem, cidadedestino, paisorigem, paisdestino, duracao, datapartida, datachegada, tipovoo, tipoaviao, matriculaaviao, companhiaaerea,escalas,observacao) VALUES ('Varig - Boeing  - MATR' , 0 , 0 , 'https://autoentusiastas.com.br/ae/wp-content/uploads/2020/03/ae0364b6f1b83ce6f17cd9e459d3de7a.jpg' , 'Brasilia' , 'Congonhas' , 'Brasilia' , 'São Paulo' , 'Brasil' , 'Brasil' , 100 , '05/07/1990' , '05/07/1990' , 'nacional' , 'Boeing ' , 'MATR' , 'Varig' , '' , 'Implantacao Comten')

